modLoader = "javafml"
loaderVersion = "[1,)"

license = "MPL-2.0"

[[mods]]
modId = "asr"
version = "${file.jarVersion}"
displayName = "Annoying Stuff Remover"
logoFile = "icon.png"
logoBlur = false
authors = "ctrlaltmilk"
description = """
Removes annoying stuff.
"""

[[mixins]]
config = "asr.mixins.json"
